export const getStudentStyles = (colors) => ({
        page: { display: 'flex', minHeight: '100vh', fontFamily: "'Outfit', 'Inter', sans-serif", background: colors.bg },
        sidebar: { width: '260px', background: colors.bgCard, backdropFilter: 'blur(10px)', borderRight: `1px solid ${colors.border}`, display: 'flex', flexDirection: 'column', padding: '26px 20px 28px', position: 'fixed', left: 0, top: 0, height: '100vh', zIndex: 10, transition: 'background 0.3s, border-color 0.3s' },
        headerBox: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '28px' },
        actionsBox: { display: 'flex', alignItems: 'center', gap: '10px' },
        iconBtn: { background: colors.bgInput, border: `1px solid ${colors.border}`, cursor: 'pointer', fontSize: '18px', padding: '10px', borderRadius: '14px', transition: 'background 0.2s' },
        logoBox: { display: 'flex', alignItems: 'center', gap: '12px' },
        logo: { width: '42px', height: '42px', borderRadius: '14px', background: `linear-gradient(135deg, ${colors.primary}, ${colors.accent})`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', color: '#fff', fontSize: '18px' },
        logoText: { color: colors.text, fontWeight: '700', fontSize: '16px' },
        nav: { display: 'flex', flexDirection: 'column', gap: '10px', flex: 1, overflowY: 'auto', paddingRight: '4px' },
        navItem: { textDecoration: 'none', textAlign: 'left', background: 'transparent', border: 'none', color: colors.textMuted, padding: '14px 16px', borderRadius: '18px', fontSize: '14px', fontWeight: '600', cursor: 'pointer', transition: 'all 0.2s ease', outline: 'none', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '10px', minHeight: '52px', borderLeft: '4px solid transparent' },
        navBadge: { color: '#fff', borderRadius: '999px', padding: '6px 12px', fontSize: '11px', fontWeight: '700', minWidth: '28px', textAlign: 'center', lineHeight: 1 },
        sidebarUserCard: { display: 'flex', alignItems: 'center', gap: '14px', padding: '20px 16px', marginTop: '24px', borderRadius: '22px', background: colors.bgInput, border: `1px solid ${colors.border}`, boxShadow: `0 15px 35px ${colors.bgInput}20` },
        sidebarAvatar: { width: '42px', height: '42px', borderRadius: '50%', background: `linear-gradient(135deg, ${colors.primary}, ${colors.accent})`, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontWeight: '800', fontSize: '16px', flexShrink: 0 },
        sidebarUserMeta: { display: 'flex', flexDirection: 'column', overflow: 'hidden' },
        sidebarUserName: { color: colors.text, fontSize: '14px', fontWeight: '700', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
        sidebarUserEmail: { color: colors.textMuted, fontSize: '12px', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
        catalogBtn: { width: '100%', background: `linear-gradient(135deg, ${colors.primary}, ${colors.accent})`, border: 'none', color: '#fff', borderRadius: '16px', padding: '14px 16px', cursor: 'pointer', fontSize: '14px', fontWeight: '700', transition: 'transform 0.2s' },
        homeBtn: { width: '100%', background: colors.bgInput, border: `1px solid ${colors.border}`, color: colors.text, borderRadius: '16px', padding: '14px 16px', cursor: 'pointer', fontSize: '14px', fontWeight: '700', transition: 'background 0.2s' },
        logoutBtn: { width: '100%', background: '#ffffff', border: '1px solid rgba(239,68,68,0.45)', color: '#b91c1c', boxShadow: '0 8px 20px rgba(239,68,68,0.12)', borderRadius: '16px', padding: '14px 16px', cursor: 'pointer', fontSize: '14px', fontWeight: '700', textAlign: 'center' },
        sidebarBottom: { display: 'flex', flexDirection: 'column', gap: '12px', marginTop: 'auto' },
        main: { marginLeft: '260px', flex: 1, padding: '32px 48px', overflowY: 'auto' },
        header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '32px' },
        greeting: { color: colors.text, fontSize: '32px', fontWeight: '900', margin: 0, letterSpacing: '-0.5px' },
        subGreeting: { color: colors.textMuted, fontSize: '14px', margin: '6px 0 0' },
        avatar: { width: '48px', height: '48px', borderRadius: '50%', background: `linear-gradient(135deg, ${colors.primary}, ${colors.accent})`, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontWeight: '800', fontSize: '20px' },
        loadingBox: { color: colors.textMuted, fontSize: '16px', textAlign: 'center', padding: '100px 0' },
        tabHeader: { marginBottom: '32px' },
        tabTitle: { color: colors.text, fontSize: '22px', fontWeight: '800', margin: 0 },
        tabSubtitle: { color: colors.textMuted, fontSize: '14px', margin: '6px 0 0' },
        statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px' },
        statCard: { background: colors.bgInput, borderRadius: '16px', padding: '20px', border: `1px solid ${colors.border}` },
        statValue: { display: 'block', fontSize: '28px', fontWeight: '800' },
        statLabel: { color: colors.textMuted, fontSize: '12px', fontWeight: '500', marginTop: '4px', display: 'block' },
        panelCard: { background: colors.bgCard, borderRadius: '12px', padding: '16px', border: `1px solid ${colors.border}`, marginBottom: '0', boxShadow: 'none' },
        panelCardTitle: { color: colors.text, fontSize: '15px', fontWeight: '800', margin: '0 0 12px', letterSpacing: '-0.3px' },
        recentCourseBox: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
        recentCourseLeft: {},
        recentCourseName: { color: colors.text, fontSize: '16px', fontWeight: '700', margin: '8px 0 4px' },
        recentCourseMeta: { color: colors.textMuted, fontSize: '13px', margin: 0 },
        recentCourseRight: { display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '8px' },
        progressPercent: { color: colors.primary, fontSize: '14px', fontWeight: '700' },
        resumeBtn: { background: `linear-gradient(135deg, ${colors.primary}, ${colors.accent})`, color: '#fff', border: 'none', borderRadius: '8px', padding: '10px 20px', fontWeight: '700', cursor: 'pointer', fontSize: '14px' },
        lockedBtn: { background: colors.bgInput, color: colors.warning, border: `1px solid ${colors.warning}30`, borderRadius: '8px', padding: '10px 20px', fontWeight: '700', cursor: 'pointer', fontSize: '14px' },
        emptyContent: { textAlign: 'center', padding: '60px 24px' },
        emptyText: { color: colors.textMuted, fontSize: '14px', marginBottom: '20px' },
        ctaLink: { color: colors.primary, textDecoration: 'none', fontWeight: '700', fontSize: '14px' },
        courseGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '24px' },
        courseCard: { background: colors.bgCard, borderRadius: '16px', padding: '24px', border: `1px solid ${colors.border}`, display: 'flex', flexDirection: 'column' },
        courseBadge: { background: `${colors.primary}15`, color: colors.primary, padding: '4px 10px', borderRadius: '20px', fontSize: '11px', fontWeight: '700', alignSelf: 'flex-start', marginBottom: '12px' },
        courseTitle: { color: colors.text, fontSize: '16px', fontWeight: '700', marginBottom: '16px', lineHeight: '1.4' },
        progressBar: { background: colors.bgInput, borderRadius: '99px', height: '6px', marginBottom: '8px' },
        progressFill: { background: `linear-gradient(90deg, ${colors.primary}, ${colors.accent})`, height: '6px', borderRadius: '99px' },
        progressText: { color: colors.textMuted, fontSize: '12px', marginBottom: '20px' },
        watchBtn: { width: '100%', background: `linear-gradient(135deg, ${colors.primary}, ${colors.accent})`, color: '#fff', border: 'none', borderRadius: '8px', padding: '10px', fontWeight: '700', cursor: 'pointer', fontSize: '14px' },
        lockedBadge: { background: `${colors.warning}15`, border: `1px solid ${colors.warning}30`, color: colors.warning, borderRadius: '8px', padding: '10px', fontSize: '13px', textAlign: 'center', fontWeight: '600' },
        tableCard: { background: colors.bgCard, borderRadius: '16px', border: `1px solid ${colors.border}`, overflow: 'hidden' },
        table: { width: '100%', borderCollapse: 'collapse', textAlign: 'left' },
        thRow: { background: colors.bgInput },
        th: { padding: '16px 24px', color: colors.textMuted, fontSize: '13px', fontWeight: '700' },
        tr: { borderBottom: `1px solid ${colors.border}` },
        td: { padding: '16px 24px', color: colors.text, fontSize: '14px' },
        tdScore: { padding: '16px 24px', color: colors.primary, fontSize: '14px', fontWeight: '700' },
        certCard: { background: colors.bgCard, borderRadius: '16px', padding: '32px', border: `1px solid ${colors.border}`, textAlign: 'center' },
        certIcon: { fontSize: '48px', marginBottom: '16px' },
        certTitle: { color: colors.text, fontSize: '18px', fontWeight: '700', marginBottom: '8px' },
        certMeta: { color: colors.textMuted, fontSize: '13px', marginBottom: '24px' },
        downloadBtn: { background: colors.success, color: '#fff', border: 'none', borderRadius: '8px', padding: '10px 20px', fontWeight: '700', cursor: 'pointer', fontSize: '14px' },
        successAlert: { background: `${colors.success}15`, border: `1px solid ${colors.success}30`, color: colors.success, padding: '12px 16px', borderRadius: '8px', marginBottom: '24px', fontSize: '14px', fontWeight: '600' },
        form: { display: 'flex', flexDirection: 'column', gap: '20px', maxWidth: '400px' },
        formGroup: { display: 'flex', flexDirection: 'column', gap: '8px' },
        label: { color: colors.textMuted, fontSize: '13px', fontWeight: '600' },
        input: { background: colors.bgInput, border: `1px solid ${colors.border}`, color: colors.text, padding: '12px 14px', borderRadius: '8px', fontSize: '14px', outline: 'none' },
        select: { background: colors.bgInput, border: `1px solid ${colors.border}`, color: colors.text, padding: '12px 14px', borderRadius: '8px', fontSize: '14px', outline: 'none' },
        saveBtn: { background: colors.primary, color: '#fff', border: 'none', borderRadius: '8px', padding: '12px', fontWeight: '700', cursor: 'pointer', fontSize: '14px', alignSelf: 'flex-start' },
        goalItem: { padding: '16px', borderRadius: '12px', background: colors.bgInput, border: `1px solid ${colors.border}`, display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
        
        // ── New Dashboard Layout & Widget Styles ───────────────────
        gridTwoCol: { display: 'grid', gridTemplateColumns: '2.5fr 1fr', gap: '20px', alignItems: 'start' },
        dashboardGrid: { display: 'flex', flexDirection: 'column', gap: '18px' },
        welcomeCard: { background: `linear-gradient(135deg, ${colors.primary}08, ${colors.accent}12)`, border: `1px solid ${colors.primary}15`, borderRadius: '18px', padding: '28px 32px', position: 'relative', overflow: 'hidden' },
        quoteText: { fontStyle: 'italic', fontSize: '13px', color: colors.textMuted, margin: '8px 0 0', opacity: 0.9 },
        deadlineList: { display: 'flex', flexDirection: 'column', gap: '10px' },
        deadlineItem: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 16px', borderRadius: '10px', background: colors.bgInput, border: `1px solid ${colors.border}` },
        priorityBadge: { padding: '4px 10px', borderRadius: '6px', fontSize: '10px', fontWeight: '800', textTransform: 'uppercase' },
        liveGrid: { display: 'flex', flexDirection: 'column', gap: '10px' },
        liveCard: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '14px 16px', borderRadius: '10px', background: colors.bgInput, borderLeft: `4px solid ${colors.accent}`, border: `1px solid ${colors.border}` },
        liveBtn: { background: colors.accent, color: '#fff', border: 'none', borderRadius: '6px', padding: '6px 12px', fontSize: '12px', fontWeight: '700', cursor: 'pointer' },
        tabSwitch: { display: 'flex', borderBottom: `1px solid ${colors.border}`, marginBottom: '18px' },
        tabSwitchBtn: { background: 'none', border: 'none', padding: '10px 16px', fontSize: '14px', fontWeight: '700', cursor: 'pointer', outline: 'none' },
        feedList: { display: 'flex', flexDirection: 'column', gap: '10px', maxHeight: '320px', overflowY: 'auto' },
        feedItem: { padding: '12px 14px', borderRadius: '10px', background: colors.bgInput, border: `1px solid ${colors.border}`, fontSize: '13px' },
        feedItemMeta: { display: 'flex', justifyContent: 'space-between', fontSize: '11px', color: colors.textMuted, marginTop: '6px' },
        recommendGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))', gap: '12px' },
        recommendCard: { background: colors.bgInput, border: `1px solid ${colors.border}`, borderRadius: '12px', padding: '16px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' },
        calendarContainer: { background: colors.bgCard, borderRadius: '14px', padding: '18px', border: `1px solid ${colors.border}` },
        calendarHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '14px' },
        calendarMonthYear: { fontWeight: '800', color: colors.text, fontSize: '14px' },
        calendarWeekdays: { display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: '4px', textAlign: 'center', marginBottom: '8px' },
        calendarWeekday: { fontSize: '11px', fontWeight: '700', color: colors.textMuted },
        calendarGrid: { display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: '4px' },
        calendarCell: { height: '32px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', borderRadius: '6px', fontSize: '12px', position: 'relative', cursor: 'pointer' },
        calendarEmptyCell: { height: '32px' },
        streakGrid: { display: 'flex', gap: '8px', marginTop: '12px' },
        streakDay: { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '8px 4px', borderRadius: '8px', fontSize: '11px', fontWeight: '700' },
        badgesContainer: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(130px, 1fr))', gap: '10px' },
        badgeCard: { padding: '14px', borderRadius: '11px', border: `1px solid ${colors.border}`, textAlign: 'center', transition: 'transform 0.2s', position: 'relative' },
        badgeIcon: { fontSize: '30px', marginBottom: '8px' },
        badgeName: { fontSize: '12px', fontWeight: '700', color: colors.text, display: 'block' },
        badgeDesc: { fontSize: '10px', color: colors.textMuted, marginTop: '4px', display: 'block', lineHeight: '1.3' },
        aiWidgetHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '16px', flexWrap: 'wrap' },
        aiActionBtn: { background: colors.accent, color: '#fff', border: 'none', borderRadius: '10px', padding: '10px 18px', fontWeight: '700', cursor: 'pointer', fontSize: '12px' },
        aiPromptTag: { background: colors.bgInput, border: `1px solid ${colors.border}`, borderRadius: '999px', padding: '8px 14px', color: colors.text, fontSize: '12px', fontWeight: '600', cursor: 'pointer', whiteSpace: 'nowrap' },
        analyticsCard: { background: colors.bgInput, borderRadius: '12px', padding: '14px', minHeight: 'auto' }
});
